name: Build and Run OpenAiCodeReview By Main Maven Jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 检出最后两个提交，以便可以比较 HEAD~1 和 HEAD

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # 你可以选择其他发行版，如 'adopt' 或 'zulu'
          java-version: '11'

      - name: Create lib dictionary
        run: mkdir -p ./libs

      - name: Download openai-code-review-sdk.jar
        run: wget -0 ./libs/openai-code-review-sdk-1.0.jar https://github.com/vadymsun/openai-code-review-log/releases/download/v1.0/openai-code-review-sdk-1.0.jar

      - name: Run code review
        run: java -jar ./libs/openai-code-review-sdk-1.0.jar
        env:
          GITHUB_TOKEN: ${{secrets.CODE_TOKEN}}